r"""Out of quota is not out of order, and the desk said it was.

OBSERVED LIVE 2026-08-28. The analyst went blind after 14:15 and the ledger's
own explanation read:

    result:  "You've hit your session limit · resets 8:10pm (Europe/Berlin)"
    reading: "the API was never called -- this is a LOCAL failure (input, login
              or binary), not a limit or an outage"

The `result` says limit. The `reading` says NOT a limit, confidently, in the one
field anybody would read. It was generated by a heuristic that treats zero
tokens plus zero API duration as proof of a local rejection — which is true of a
rejected flag and an expired login, and equally true of a quota refusal, because
the CLI declines all three before sending anything.

That collision cost twice. The flag ladder walks four rungs on a local
rejection, so every wake spent FIVE invocations against a limit that was already
exhausted — the one failure mode that gets strictly worse when retried.

WHAT MAKES THIS FAULT DIFFERENT FROM EVERY OTHER ONE THE DESK REPORTS: nothing
is broken. No restart, re-login or reinstall helps, and the limit resets on a
clock. The only correct actions are to stop retrying and to say so.

    python3 -m pytest test_quota_exhausted.py -q
"""

from __future__ import annotations

import json
import sys
from datetime import datetime, timezone
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).parent))

from golddesk.analyst_health import check_quota
from golddesk.providers import AnalystError, ClaudeCodeAnalyst

NOW = datetime(2026, 8, 28, 18, 0, tzinfo=timezone.utc)

#: Verbatim from the box.
QUOTA = json.dumps({
    "is_error": True, "duration_api_ms": 0, "num_turns": 1,
    "stop_reason": "stop_sequence", "subtype": "success",
    "session_id": "94bdc1c9-883f-4c15-82c2-0441f47b0b24", "total_cost_usd": 0,
    "usage": {"input_tokens": 0, "output_tokens": 0},
    "result": "You've hit your session limit · resets 8:10pm (Europe/Berlin)",
})

FLAG_REJECT = json.dumps({
    "is_error": True, "duration_api_ms": 0, "stop_reason": "stop_sequence",
    "usage": {"input_tokens": 0, "output_tokens": 0}})


def _runner(failure):
    seen = []

    def run(argv, prompt):
        seen.append(list(argv))
        return (1, failure, "")

    return run, seen


# --------------------------------------------------------------------------
# It is recognised, and the reset time survives.

def test_a_session_limit_is_recognised():
    assert ClaudeCodeAnalyst._quota_exhausted(QUOTA, "") is not None


def test_the_reset_time_survives_into_the_error():
    """'resets 8:10pm' is the entire actionable content — it is the only thing
    that says when reads come back."""
    p = ClaudeCodeAnalyst(runner=_runner(QUOTA)[0])
    with pytest.raises(AnalystError) as ei:
        p._invoke("BRIEF")
    assert "8:10pm" in str(ei.value)


def test_it_is_not_mistaken_for_a_login_failure():
    """Both refuse before spending a token. Only the message separates them, and
    sending somebody to re-login during a quota reset wastes the one thing this
    check exists to save."""
    assert ClaudeCodeAnalyst._auth_failure(QUOTA, "") is None


def test_a_clean_success_is_not_a_quota_failure():
    ok = json.dumps({"subtype": "success", "result": "{}",
                     "duration_api_ms": 9100,
                     "usage": {"input_tokens": 910, "output_tokens": 61}})
    assert ClaudeCodeAnalyst._quota_exhausted(ok, "") is None


# --------------------------------------------------------------------------
# THE EXPENSIVE HALF: it must not walk the ladder.

def test_a_quota_refusal_does_not_walk_the_flag_ladder():
    """Four rungs is four more calls against a limit that is already gone. This
    is the one failure that gets strictly WORSE when retried."""
    run, seen = _runner(QUOTA)
    p = ClaudeCodeAnalyst(runner=run)
    with pytest.raises(AnalystError):
        p._invoke("BRIEF")
    assert len(seen) == 1, f"spent {len(seen)} calls on an exhausted quota"
    assert p._flag_drop == 0, "the arm was degraded by running out of quota"


def test_a_genuine_flag_rejection_still_walks_it():
    """The fix must not disable the ladder — the envelopes are identical and
    only the message differs."""
    run, seen = _runner(FLAG_REJECT)
    with pytest.raises(AnalystError):
        ClaudeCodeAnalyst(runner=run)._invoke("BRIEF")
    assert len(seen) > 1


def test_the_error_says_no_retry_helps():
    p = ClaudeCodeAnalyst(runner=_runner(QUOTA)[0])
    with pytest.raises(AnalystError) as ei:
        p._invoke("BRIEF")
    msg = str(ei.value)
    assert "NOT a flag, a login or an outage" in msg
    assert "rule-based arm" in msg


# --------------------------------------------------------------------------
# The ledger row stops contradicting itself.

def test_the_blind_row_no_longer_calls_a_limit_a_local_failure():
    from golddesk.live import _explain_analyst_error
    p = ClaudeCodeAnalyst(runner=_runner(QUOTA)[0])
    with pytest.raises(AnalystError) as ei:
        p._invoke("BRIEF")
    detail = _explain_analyst_error(ei.value)
    assert detail.get("quota_exhausted") is True
    assert "SESSION LIMIT" in detail["reading"]
    assert "not a limit" not in detail["reading"].lower()


# --------------------------------------------------------------------------
# The watchdog names it as its own fault, with the opposite remedy.

def _blind(ts, result="You've hit your session limit · resets 8:10pm"):
    return {"t0": ts, "kind": "BLIND", "decision": {"cli": {"result": result}}}


def test_the_audit_reports_quota_as_its_own_fault():
    f = check_quota([_blind("2026-08-28T15:00:00+00:00")], NOW)
    assert not f.ok
    assert "SUBSCRIPTION QUOTA EXHAUSTED" in f.detail


def test_it_says_nothing_is_broken():
    """Every other fault here means something needs fixing. This one means the
    opposite, and saying so stops an operator restarting a healthy desk."""
    f = check_quota([_blind("2026-08-28T15:00:00+00:00")], NOW)
    assert "NOTHING IS BROKEN" in f.detail
    assert "no restart or re-login helps" in f.detail


def test_it_carries_the_reset_time_to_the_operator():
    f = check_quota([_blind("2026-08-28T15:00:00+00:00")], NOW)
    assert "8:10pm" in f.detail


def test_it_clears_once_the_analyst_answers_again():
    """The limit resets on a clock, so this check MUST be able to go green
    without anybody doing anything."""
    rows = [_blind("2026-08-28T15:00:00+00:00"),
            {"t0": "2026-08-28T17:00:00+00:00", "kind": "SIGNAL",
             "decision": {"provider": "claudecode"}}]
    f = check_quota(rows, NOW)
    assert f.ok
    assert "RECOVERED" in f.detail


def test_an_ordinary_blind_row_is_not_called_a_quota_problem():
    f = check_quota([_blind("2026-08-28T15:00:00+00:00",
                            result="claude timed out after 600s")], NOW)
    assert f.ok


def test_the_two_marker_lists_agree():
    """Two files encoding one vocabulary is how a detector and its watchdog
    start disagreeing about the same event."""
    from golddesk.analyst_health import QUOTA_MARKERS
    assert set(QUOTA_MARKERS) <= set(ClaudeCodeAnalyst.QUOTA_MARKERS)



def test_an_expired_login_is_not_read_as_a_quota_problem():
    """CAUGHT BY THE SUITE. The desk's own auth error says "THIS IS NOT A FLAG,
    A RATE LIMIT OR AN OUTAGE" — and the quota detector, scanning the whole
    message, matched "rate limit" inside the sentence DENYING one. The desk's
    explanation of a fault was being read as evidence of a different fault, and
    the remedies point in opposite directions: one needs a human at a browser,
    the other needs everyone to wait and stop retrying."""
    from golddesk.live import _explain_analyst_error
    expired = json.dumps({
        "is_error": True, "duration_api_ms": 0, "subtype": "success",
        "usage": {"input_tokens": 0, "output_tokens": 0},
        "result": "Failed to authenticate: OAuth session expired and could not "
                  "be refreshed"})
    p = ClaudeCodeAnalyst(runner=_runner(expired)[0])
    with pytest.raises(AnalystError) as ei:
        p._invoke("BRIEF")
    detail = _explain_analyst_error(ei.value)
    assert detail.get("needs_login") is True
    assert detail.get("quota_exhausted") is None

if __name__ == "__main__":
    sys.exit(pytest.main([__file__, "-q"]))
